from django.core.exceptions import ValidationError
import re

def validate_name(name):
    pass